server:
  port: 8081
news:
  url: "https://news.google.com/?hl=zh-TW&gl=TW&ceid=TW:zh-Hant"
spring:
  redis:
    host: "localhost"
    port: 6379
    pool:
      max-active: 8
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      temp:
        use_jdbc_metadata_defaults: false
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/news
    username: postgres
    password: 123456